### ISSUE TITLE
Disable Avatax module for a website suppress paypal options in admin panel

### ISSUE THREAD

**Issue by varun931** [onepica/avatax#272]
when i disable avatax module for a website, my paypal options are not visible in admin panel. However when this is disable for a store, paypal options remains intact.

Avatax module version : 2.4.3.1

**Comment by marynychsv** [comment]
Greetings,

Please, write to Avalara support (https://www.avalara.com/support/). 
They will create support ticket for your issue and we will be able to investigate it, request additional information from you and etc.
		
Currently we could only say that you are using a very old version of AvaTax extension.
We had lot of bug fixes since 2.4.3.1 version.
